### PR TITLE
Label specific flags with --labelflags or label_flags in config file

### PR DESCRIPTION
**Pull request by wkentaro**
Merge https://github.com/wkentaro/labelme/pull/388 to the `master` branch.

@cmerchant I've decided to use regex for the keys of `label_flags` since it is much general, and can be easily adapted to instance segmentation.
See instance segmentation example in 2d05f31.

```bash
# examples/instance_segmentation
labelme data_annotated --labels labels.txt --nodata --labelflags '{.*: [occluded, truncated], person-\d+: [male]}'
```

### CODE REVIEW

**Comment by cmerchant** [comment]
@wkentaro must be a different cmerchant ?

**Comment by wkentaro** [comment]
Sorry what do you mean?

**Comment by cmajor28** [comment]
@wkentaro I think we meant to tag me. This change looks useful.

**Comment by wkentaro** [comment]
Oh, got it. Sorry about that. And thanks for the PR.

**Comment by pierrelzw** [comment]
hi @wkentaro is that possible to set difference labelflags for different labels? 
I test this instance segmentation example, but i can only add 'occluded' or 'truncated' for all classes.
image

**Comment by wkentaro** [comment]
@pierrelzw https://github.com/wkentaro/labelme/pull/872 will fix this.

**Comment by cloudlakecho** [comment]
@pierrelzw Thanks for bring up the new feature in the tool. 

Are you eventually be able to add multiple label in one bounding box with 
` $ labelme data_annotated --labels labels.txt --nodata --labelflags '{sofa-\d+: [occluded, truncated], person-\d+: [male]}`?

If yes, would you share how to execute the command line? In my runtime environemnt, I am facing this error: 
```
(labelme) c:\data\with scene\label>labelme data_annotated --labels google_0002.json --nodata --labelflags '{sofa-\d+: [occluded, truncated], person-\d+: [male]}                                         
usage: labelme [-h] [--version] [--reset-config]
                       [--logger-level {debug,info,warning,fatal,error}]   
                       [--output OUTPUT] [--config CONFIG] [--nodata] [--autosave]
                       [--nosortlabels] [--flags FLAGS] [--labelflags LABEL_FLAGS] 
                       [--labels LABELS] [--validatelabel {exact}] [--keep-prev]  
                       [--epsilon EPSILON]  
                       [filename]                                                                                               
labelme: error: unrecognized arguments: [occluded, truncated], person-\d+: [male]}  
```

I am also not able to make TXT format label (only JSON) in LabelMe tool. How did you make the TXT file format label? 

My runtime environment:
&nbsp;&nbsp; Python 3.6
&nbsp;&nbsp; LabelMe 5.0.1

**Pull request merged**
