### PR TITLE
Revert "Revert "Deselect shape when clicking and already selected""

### PR DESCRIPTION
**Pull request by markub3327**
Reverts wkentaro/labelme#949

@wkentaro 

Here bottle is too tight and epsilon too high (I can't effectively pick the object) .... I try to go back to last commit and for me everything is working. In this video you can see why this shape is not good for testing.

Thanks have a nice day.

https://user-images.githubusercontent.com/74611856/140948458-303bd3a9-1642-4e8a-91d4-093fadf9a624.mp4

### CODE REVIEW

**Comment by wkentaro** [comment]
I know it works, but we have to keep the mouse clicked, right?
I sometimes release the mouse while dragging and click again to continue moving the selected shapes. However, with the current implementation, it deselects the polygon the mouse is hovering and disables the movement of that.

**Comment by wkentaro** [comment]
I'm not saying deselection is a bad idea, but deselecting with Ctrl+Click would be inconvenient because of the above reason.
In MS PowerPoint, the multi-object selection is done by Ctrl+Click, movement is done by Click+drag (instead of Ctrl+Click+drag), deselection is done by Ctrl+click or Clicking blank area. Maybe we can follow this UI.

**Comment by markub3327** [comment]
> I know it works, but we have to keep the mouse clicked, right?
> I sometimes release the mouse while dragging and click again to continue moving the selected shapes. However, with the current implementation, it deselects the polygon the mouse is hovering and disables the movement of that.

You don't have true. I test it again with release mouse button and the shape is not deselected. And when I select multiple object use Ctrl+Click, but when I move with them I use only Click+drag. Please try this version of code again... The deselecting was not activate because this if statement:
```python
                 if (
                     self.hShape is not None
                     and self.wasSelected
                     and not self.movingShape
                 ):
                     self.selectionChanged.emit(
                         [x for x in self.selectedShapes if x != self.hShape]
                     )
```

**Comment by wkentaro** [comment]
Thanks. With the latest commit 4c23f44, it works as I expect.
Is that collect that `self.wasSelected` is used for distinguishing the state of `self.hShape` whether that is hovered or selected? If so, please rename that to something like `self.hShapeIsSelected`.

**Comment by markub3327** [comment]
Yeah, you have a true 😊 .... I renamed it.

Thanks.
Have a nice day.

**Review by wkentaro — APPROVED** [review]

**Pull request merged**
