### PR TITLE
Fix label encoding error across platforms (#299)

### PR DESCRIPTION
**Pull request by TomHeaven**
This PR aims to solve issue https://github.com/wkentaro/labelme/issues/299. On Windows, files are saved with GB2312 as default encoding. However, utf-8 is the default encoding on Linux and macOS. With previous version of labelme, if you label images on Windows and open the label json files on Linux or macOS, you will encounter issue https://github.com/wkentaro/labelme/issues/299.

This PR solve the issue by setting the default encoding of label files as utf-8. Therefore, no matter on what OS, you will not meet https://github.com/wkentaro/labelme/issues/299 using the new version.

Besides, this PR offers an extra option "--label_encoding" to make Labelme compatible with previous json files of labels. For instance, if you make labels on Windows using previous versions of Labelme and need to open them on macOS, simply start this version by
```
labelme --label_encoding gb2312
```
and it should work like a charm.

### CODE REVIEW

**Comment by wkentaro** [comment]
Do you have any example windows file for testing?

**Comment by TomHeaven** [comment]
Yes, I do. In fact, i've already tested the PR with those files, and it works.

**Comment by wkentaro** [comment]
I mean when https://github.com/wkentaro/labelme/pull/683 is not enough?
Also, you can see the CI is not passing with Python2.

**Comment by TomHeaven** [comment]
I'll email u some data later. I think it's time to give up Python 2 since it is deprecated for half a year.

**Comment by wkentaro** [comment]
I found the below command works for old files.
```
iconv -f gb18030 -t utf-8 1.json > 1_utf8.json
```

**Comment by Bjoux2** [comment]
> This PR aims to solve issue #299. On Windows, files are saved with GB2312 as default encoding. However, utf-8 is the default encoding on Linux and macOS. With previous version of labelme, if you label images on Windows and open the label json files on Linux or macOS, you will encounter issue #299.
> 
> This PR solve the issue by setting the default encoding of label files as utf-8. Therefore, no matter on what OS, you will not meet #299 using the new version.
> 
> Besides, this PR offers an extra option "--label_encoding" to make Labelme compatible with previous json files of labels. For instance, if you make labels on Windows using previous versions of Labelme and need to open them on macOS, simply start this version by
> 
> ```
> labelme --label_encoding gb2312
> ```
> 
> and it should work like a charm.


withi this:
#with open(filename, 'rb' if PY2 else 'r') as f:
with open(filename, encoding='gb2312') as f: # To read windows labels.

I got the result:

Error opening file
Open() got an unexpected keyword argument 'encoding'

**Pull request closed without merging**
