### PR TITLE
Support Ctrl/Command Key + mouse scrolling for zoom in/out

### PR DESCRIPTION
**Pull request by wkentaro**
Close https://github.com/wkentaro/labelme/issues/37

This is supported on PyQt4, but not supported with PyQt5. So I recognize this as a kind of bug.

### CODE REVIEW

**Comment by ron-weiner** [comment]
hey
i don't understand if is it possible to use those features, it's not working for me...
I saw the code uses PyQt5, so is there an existing merged fix for that?
If not, is it in progress?

thanks a lot!

**Comment by serycjon** [comment]
I have a hacky fix here: https://github.com/serycjon/labelme/commit/64140bc8f0ee717a5951649631726e410fa6f94a

**Comment by ron-weiner** [comment]
Great thanks! I will check it soon.
Do you also have something for "dragging image view"?

**Comment by serycjon** [comment]
No, but scrolling around the image with mousewheel (vertical) and shift+mousewheel (horizontal) should work with that patch.

**Comment by ron-weiner** [comment]
Great I will try it tomorrow.
Thanks a lot!

**Comment by ron-weiner** [comment]
it is working just as you said, thanks a lot!

**Pull request merged**
