### PR TITLE
Add rotate right and rotate left button in edit menu

### PR DESCRIPTION
**Pull request by ctudoudou**
I found the function that needs to be rotated when I use it, so I added these two functions.

Thanks.

### CODE REVIEW

**Comment by wkentaro** [comment]
Hmm. I don't think it is a good idea to edit the original image file.
According to https://github.com/wkentaro/labelme/issues/232, the reason why you need to rotate is the python script does not correctly read EXIF information.
I think we should add fix to read EXIF before thinking of adding this kind of feature.

**Comment by ctudoudou** [comment]
I think I fix the #232.

Thanks.

**Comment by wkentaro** [comment]
Thanks. I created a refactored version at https://github.com/wkentaro/labelme/pull/305.

**Comment by ryouchinsa** [comment]
RectLabel is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can remove the EXIF orientation flags from images and convert images to the front orientation. If necessary, you can rotate the image right/left by 90 degrees.
https://rectlabel.com/help#remove_exif_orientation_flags

**Pull request closed without merging**
