### PR TITLE
Group operations on shapes (#405) 

### PR DESCRIPTION
**Pull request by wkentaro**
Merge https://github.com/wkentaro/labelme/pull/405

### CODE REVIEW

**Comment by wkentaro** [comment]
@IlyaOvodov I found that Ctrl-Z doesn't work if I move multiple polygons at the same time, and this code only handles less than 3 polygons, right?
Could you make these fixed?

**Comment by IlyaOvodov** [comment]
I checked both and didn't find any problems either with handling 3,4,5 and even 6 polygons or with undoing it. Where did you find magic number "3"?

**Comment by wkentaro** [comment]
Oh, sorry, maybe I was doing something wrong. When I tried again, it works without any problems.
One thing I'm not sure and why I thought about the magic number "3" is because of this line:
https://github.com/wkentaro/labelme/pull/412/files#diff-e970378747e9d6872c94dbcf67a84e62R334

Why did you need to add another menu to the canvas here?
https://github.com/wkentaro/labelme/pull/412/files#diff-e970378747e9d6872c94dbcf67a84e62R70

**Comment by IlyaOvodov** [comment]
> Why did you need to add another menu to the canvas here?
Primaraly I expected that I will implement only Move for grope of shapes, but copy (and duplicate) will be available only if only 1 shape is selected (as I thought that it require some shape-specific uses dialog). So I made 2 different popup menus. But then I found that it is no problem to copy group of shapes as well, so these 2 menus became similar. But I decided not to remove this option, possibly it can be useful in a future. If You prefer to revert it, just correct 2 lines you pointed above (change 2 to 1 in the 1st one and revert the 2nd one) and also revert menu[2] initialization.

**Pull request merged**
