### PR TITLE
add circle shapes support

### LINKED ISSUE #129: Can we add the possibility for circle annotation?
Hey!
Thanks for the great tool again!

I sought for the possibility to make circle annotations, i find it very useful because in some cases there is a perfect circle we wish to annotate and its less productive and less accurate to mark it all with lots of dots..

Is there some existing solution with labelme? is it part of the pipeline?

thanks

### PR DESCRIPTION
**Pull request by latticetower**
Hi, I've added circle annotations (which probably fixes #129 ), could you take a look?

### CODE REVIEW

**Comment by wkentaro** [comment]
Thanks! I'll take a look soon.

**Comment by wkentaro** [comment]
@latticetower I tested and it works for circle annotation. Nice work. Thanks.
But the rectangle annotation breaks after this change. Could you take a look to fix it?

**Comment by wkentaro** [comment]
@latticetower I cherry-picked a commit of yours (#237), so could you rebase with origin/master?

**Comment by latticetower** [comment]
@wkentaro I will check it

**Comment by wkentaro** [comment]
@latticetower Thanks!

**Pull request closed without merging**
