### PR TITLE
Translation/i18n support

### PR DESCRIPTION
**Pull request by zhangchn**
I18n support was implemented with `QTranslator` utility and language specific ts/qm files.

A translation for Simplified Chinese was added.

To translate for more languages, make a copy of translate/empty.ts and edit the XML contents. Then run `lrelease translate/{language name}.ts` to generate the corresponding qm file.

### CODE REVIEW

**Comment by wkentaro** [comment]
Can you explain how to test? How to change to Chinese version on Ubuntu 16.04 or macOS?

**Comment by zhangchn** [comment]
To test this patch, set environment variable LC_ALL (e.g. `export LC_ALL=zh_CN.UTF-8`) and run labelme.

**Comment by wkentaro** [comment]
Sorry for late. I have tried, but can't make it work.

**Comment by wkentaro** [comment]
@zhangchn Sorry for very late. It worked when I tested again! Thanks for the PR!

**Comment by jizongFox** [comment]
@zhangchn  Hello, I have tried with the environment flag: `LC_ALL=zh_CN.UTF-8` but it seems not working for this moment. Can you have a more clear instruction on the translation ?

**Comment by zhangchn** [comment]
> @zhangchn Hello, I have tried with the environment flag: `LC_ALL=zh_CN.UTF-8` but it seems not working for this moment. Can you have a more clear instruction on the translation ?

Would you please elaborate your environment (OS version/distribution, etc.) and steps to reproduce this issue?

**Pull request merged**
