### PR TITLE
Create labelme.1

### PR DESCRIPTION
**Pull request by alexmyczko**

### CODE REVIEW

**Comment by wkentaro** [comment]
?

**Comment by alexmyczko** [comment]
it is a man(ual) page, see man man. to be put in /usr/share/man/man1/

**Comment by wkentaro** [comment]
Oh I see. Can you put it in share/man/man1 directory?

**Comment by alexmyczko** [comment]
sure i will try to change this pr

**Comment by yiyayiya1** [comment]
我做完的东西保存之后，放在一个文件夹里面，怎么无法导入呀？

**Comment by wkentaro** [comment]
Could you let me know how to generate this file?

**Comment by wkentaro** [comment]
@alexmyczko I found help2man. Thanks for PR! This will be merged via https://github.com/wkentaro/labelme/pull/439 with some logic to install the man file via pip.

**Pull request closed without merging**
